from datetime import datetime


def generate_security_report(
    email_text,
    prediction,
    confidence,
    risk_level,
    risk_score,
    attack_type,
    severity,
    indicators
):

    report = f"""
========================================
🛡️ AI PHISHING SECURITY REPORT
========================================

Generated Time:
{datetime.now()}


📧 Email Analysis
----------------------------------------

Prediction:
{prediction}

Confidence:
{confidence:.2f}%


🛡️ Threat Assessment
----------------------------------------

Risk Level:
{risk_level}

Threat Score:
{risk_score}/100


🎯 Attack Classification
----------------------------------------

Attack Type:
{attack_type}


🚨 Severity Assessment
----------------------------------------

Severity:
{severity}


⚠️ Threat Indicators
----------------------------------------
"""

    if indicators:

        for item in indicators:
            report += f"\n- {item}"

    else:

        report += "\nNo suspicious indicators detected."


    report += """

========================================
🔐 Security Recommendation
========================================

• Avoid clicking suspicious links
• Do not share passwords
• Verify sender identity
• Report suspicious emails
• Follow security best practices


========================================
Generated by:
AI-Powered Phishing Email Detector
========================================

"""

    return report